apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-uequ
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-uequ
    app.kubernetes.io/part-of: my-app-2
  name: devfile-sample-code-with-quarkus-uequ
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-uequ
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-uequ
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-engineering-jech-tenant/my-app-2/devfile-sample-code-with-quarkus-uequ@sha256:15bd1706977cce46236eb40d8aff6b6967b8c8ae1a4fac657d28183ff31ecfac
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
